apiVersion: v1
kind: Namespace
metadata:
  name: photo-spot-frontend 
---
#need to find good way to deploy prod one for main cluster
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: mvanderlyn27@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: photo-spot-frontend 
spec:
  selector:
    app: photo-spot
    tier: frontend
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80 
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: photo-spot-frontend
spec:
  selector:
    matchLabels:
      app: photo-spot
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: photo-spot
        tier: frontend
        track: stable
    spec:
      containers:
      - name: frontend
        image: "mvanderlyn27/photo-spot-frontend:latest"
#        imagePullPolicy: Always
---
#probably need to modify this to work for local, and with prod letsencrypt
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
  namespace: photo-spot-frontend
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: photo-spot.vanderlyn.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  tls:
  - hosts:
    - photo-spot.vanderlyn.space
    secretName: photo-spot-vanderlyn-space-tls