apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: mvanderlyn27/photo-spot-backend
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - backend.yaml
