apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend 
  namespace: photo-spot
spec:
  selector:
    matchLabels:
      app: photo-spot
      tier: backend
      track: stable
  replicas: 
  template:
    metadata:
      labels:
        app: photo-spot
        tier: backend
        track: stable
    spec:
      containers:
        - name: photo-spot 
          image: "mvanderlyn27/photo-spot-backend:latest"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: photo-spot
spec:
  selector:
    app: photo-spot 
    tier: backend
  type: NodePort 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32021
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
      nodePort: 32022


