apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: photo-spot 
spec:
  selector:
    app: photo-spot
    tier: frontend
  type: NodePort 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000 
      nodePort: 32001
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
      nodePort: 32002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: photo-spot
spec:
  selector:
    matchLabels:
      app: photo-spot
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: photo-spot
        tier: frontend
        track: stable
    spec:
      containers:
      - name: frontend
        image: "mvanderlyn27/photo-spot-frontend:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
            protocol: TCP