apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
  namespace: photo-spot
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: photo-spot.vanderlyn.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-backend
#   namespace: photo-spot
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: vanderlyn.space
#     http:
#       paths:
#       - path: /api/v1
#         pathType: Prefix
#         backend:
#           service:
#             name: backend 
#             port:
#               number: 80




