apiVersion: v1
kind: PersistentVolume
metadata:
  name: photo-spot-storage 
  labels:
    type: local
spec:
  storageClassName: photo-spot-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"